### ISSUE TITLE
Criação do banco de dados

### ISSUE THREAD

**Issue by guilherme-adesouza** [guilherme-adesouza/cesar#2]
Criar banco de dados com base no modelo ER abaixo. Não é necessário a criação de views, triggers e similares.

![platineiv3](https://user-images.githubusercontent.com/34776257/53995630-63bd1c00-4114-11e9-97fa-70fa2733f09b.png)

**Comment by JuniorLenhart** [comment]
Criado o script e o banco fisicamente do sistema.
